### ISSUE TITLE
Delete sensitive information using "pure" Travis

### ISSUE THREAD

**Issue by chahuistle** [qbicsoftware/cookiecutter-templates-cli#3]
Neither `after_script` nor `after_deploy` phases are executed when `before_deploy` succeeds but `deploy` fails. This means that we could potentially "leak" sensitive information by leaving files in a build that passed but could not be deployed (maybe our testing instance is not reachable).

Not sure if this is a big deal. Also, not sure what Travis does with "worker nodes" after a build has completed. **Apparently** only logs and some information about the build are available after a build finishes, regardless of its status.

The first solution that comes to my mind would be to leave the `deploy` phase like so:

```bash
deploy:
- skip_cleanup: true
  provider: script
  script: ( mvn deploy && rsync ) || rm -f sensitive_data
```
This will mean that, for Travis, all of our deploys will "succeed" (no matter what happens, the return code of the deploy script will always be `0`). This might be confusing.

Maybe there's a _Travis CI_ way to do it. More research is needed.

**Comment by naepfel** [comment]
Leaking sensitive information should be avoided by any means. Could you please specify the scenario (would users get info about our configs?) or what would the sensitive info look like? Can you please investigate solutions to it?

Thanks.


Von meinem iPad gesendet

**Comment by naepfel** [comment]
Thanks Luis. 
As you describe, it sounds OK to me. The deletion of the public key(s) should probably be written down some where as an SOP in case of breach. Potentially this SOP should then be referred in our data security concept.

**Comment by chahuistle** [comment]
Right now I am doing testing on [this repository](https://github.com/chahuistle/more-tests). Feel free to look around and let me know if you find a hole in the code. I am also open to suggestions. 

I am sorry I did not document the code, I just made a simple portlet and have been using it to do my testing before actually rolling out the code.

My tests suggest that after a build finishes, regardless of the status, the only thing available to the public is the contents of the log file. In other words, I think I found a solution that, in my opinion, works in "all reasonable and documented" scenarios. I cannot write code to prevent a disgruntled Amazon employee peeking into this conversation and then deploy maven artifacts for fun. Although that would make a good story, I guess?

**Comment by sven1103** [comment]
Now that I had some time to think about it, I think this is more and more a bad idea to use an external build provider to deploy software on our internal test-instance. I think we should just not do it, and do a wget for the current snapshot in order to deploy it. That's not a big think to do, but we have the control on our side. You could instead write a small CLI, that queries for a given maven project and pulls the most recent one. 

Best, Sven

**Comment by chahuistle** [comment]
There's always the assumption that "nothing" will go wrong. But if things go wrong, then we lose control. I am confident with the code, but then this approach is like the thermal exhaust port of the Death Star.

I like your idea. And you are right, the most important thing is that the control is on our side. We still need to encrypt some credentials for maven deployments, but that's nothing compared to having private keys floating around.

I think I will look into making this new CLI use GitHub's API via [webhooks](https://developer.github.com/webhooks/). Maybe there's something out there already. I will look into it. Travis does that in the background, it interacts with GitHub's API to get notifications when something happens. 

I think we all learned a valuable lesson here: keep it simple. I also learned to do some fancy Travis and bash stuff, which was cool. More power to me! 

I won't close this one until the first version has been rolled out, just as a reminder, don't panic!

**Comment by chahuistle** [comment]
I think I found out a way. We are using Nexus Repository Management 3. According to their documentation, they also offer [webhooks to subscribe to notifications](https://help.sonatype.com/repomanager3/webhooks).

Since our repository is inside the firewall, it has access to our testing instance without compromising anything. I guess the best and most secure non-polling solution would be a CLI tool running as a daemon on our testing instance. This tool would get notifications via HTTP whenever our maven repository changes.

No need to add extra "holes" on our firewall (our maven repo already interacts with Travis via encrypted credentials defined `.travis.yml`).

**Comment by sven1103** [comment]
I think this sounds like a good idea!

**Comment by chahuistle** [comment]
Closing it because this issue has been addressed by https://github.com/qbicsoftware/nexus-listener-service
